name: Deploy to Bluehost

on:
  push:
    branches:
      - main  # Change if you use a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean remote directory
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          # Use password authentication instead of key
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            rm -rf /home2/thencmeo/public_html/*
            mkdir -p /home2/thencmeo/public_html

      - name: Upload files via SCP
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "public/*"
          target: "/home2/thencmeo/public_html/"
          strip_components: 1

      - name: Add or update config.php files on server
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cat <<EOT > /home2/thencmeo/public_html/config/config.php
            <?php
            /*
             * Database Configuration
             */
            define("DB_HOST", "${{ secrets.DB_HOST }}");
            define("DB_USER", "${{ secrets.DB_USER }}");
            define("DB_PASSWORD", "${{ secrets.DB_PASSWORD }}");
            define("DB_DATABASE", "${{ secrets.DB_DATABASE }}");
            ?>
            EOT

            cat <<EOT > /home2/thencmeo/public_html/admin/config/config.php
            <?php
            /*
             * Database Configuration
             */
            define("DB_HOST", "${{ secrets.DB_HOST }}");
            define("DB_USER", "${{ secrets.DB_USER }}");
            define("DB_PASSWORD", "${{ secrets.DB_PASSWORD }}");
            define("DB_DATABASE", "${{ secrets.DB_DATABASE }}");
            ?>
            EOT
