name: Deploy to Bluehost

on:
  push:
    branches:
      - main  # Change if you use a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local-dir: ./  # Root of the GitHub repository
          server-dir: /public_html/  # Correct absolute path to public_html
          exclude: |
            **/.git*
            **/node_modules/**
            **/yarn.lock
            **/.github/**

      - name: Create config.php file for the root
        run: |
          echo "<?php
          /*
           * Database Configuration
           */
          define('DB_HOST', '${{ secrets.DB_HOST }}');
          define('DB_USER', '${{ secrets.DB_USER }}');
          define('DB_PASSWORD', '${{ secrets.DB_PASSWORD }}');
          define('DB_DATABASE', '${{ secrets.DB_DATABASE }}');
          ?>" > config.php

      - name: Upload config.php to /config/
        run: |
          ftp -inv ${{ secrets.HOST }} <<EOF
          user ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }}
          cd /public_html/config/
          put config.php
          bye
          EOF

      - name: Upload config.php to /admin/config/
        run: |
          ftp -inv ${{ secrets.HOST }} <<EOF
          user ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }}
          cd /public_html/admin/config/
          put config.php
          bye
          EOF

      - name: Cleanup local config.php file
        run: rm config.php
